name: Blueprint consistency check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  blueprint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r AGRISENSEFULL-STACK/agrisense_app/backend/requirements.txt || true

      - name: Run blueprint generator (ML disabled)
        env:
          AGRISENSE_DISABLE_ML: "1"
        run: |
          python AGRISENSEFULL-STACK/scripts/generate_blueprint.py || exit 2

      - name: Check for import-error placeholders
        run: |
          if grep -q "Unable to import FastAPI app" AGRISENSE_BLUEPRINT.md; then
            echo "Found import error placeholder in blueprint"; exit 3
          fi

      - name: Run fast pytest subset
        run: |
          python -m pip install pytest pillow numpy requests fastapi[all] || true
          # Install a tiny sample model (if present) so tests run deterministic inference
          if [ -f agrisense_app/backend/disease_model.joblib ]; then
            echo "Sample model present; running tests against it";
          else
            echo "No sample model found; tests may use deterministic stubs";
          fi
          AGRISENSE_DISABLE_ML=1 python -m pytest -q scripts/test_integration_disease_detect.py scripts/test_endpoint_disease_detect_client.py || exit 4

      - name: Run smoke tests (serverless)
        run: |
          python -m pip install pytest requests pillow || true
          AGRISENSE_DISABLE_ML=1 python scripts/smoke_test_endpoints.py || true
